// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/payment_management/data/models/payment_local_models/category_local_model.dart';
import 'features/payment_management/data/models/payment_local_models/payment_local_info_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6420331599651958668),
    name: 'CategoryLocalModel',
    lastPropertyId: const obx_int.IdUid(9, 3480966842126916344),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2965915122947146),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6728531053535541664),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4904786589903045449),
        name: 'color_value',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2171641816419615243),
        name: 'quantity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3779686883364740820),
        name: 'cost',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7649954701181082518),
        name: 'amount_paid',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4700928738641708438),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8002286578458877461),
        name: 'category_status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3480966842126916344),
        name: 'original_color_value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'paymentInfo',
        srcEntity: 'PaymentInfoLocalModel',
        srcField: 'category_list',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4401135258923804491),
    name: 'PaymentInfoLocalModel',
    lastPropertyId: const obx_int.IdUid(7, 7406303197173765578),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8188247300524978103),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6280263842091853691),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4576909031677871237),
        name: 'phone_number',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5262847613753833115),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 46941973628084947),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3094619609554494469),
        name: 'payment_method',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 1034562958712804097),
        name: 'category_list',
        targetId: const obx_int.IdUid(1, 6420331599651958668),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 4401135258923804491),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(2, 1034562958712804097),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [7406303197173765578],
    retiredRelationUids: const [7121663207257609299],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CategoryLocalModel: obx_int.EntityDefinition<CategoryLocalModel>(
      model: _entities[0],
      toOneRelations: (CategoryLocalModel object) => [],
      toManyRelations: (CategoryLocalModel object) => {
        obx_int.RelInfo<PaymentInfoLocalModel>.toManyBacklink(2, object.id):
            object.paymentInfo,
      },
      getId: (CategoryLocalModel object) => object.id,
      setId: (CategoryLocalModel object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryLocalModel object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final color_valueOffset = object.color_value == null
            ? null
            : fbb.writeString(object.color_value!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final category_statusOffset = object.category_status == null
            ? null
            : fbb.writeString(object.category_status!);
        final original_color_valueOffset = object.original_color_value == null
            ? null
            : fbb.writeString(object.original_color_value!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, color_valueOffset);
        fbb.addFloat64(3, object.quantity);
        fbb.addFloat64(4, object.cost);
        fbb.addFloat64(5, object.amount_paid);
        fbb.addOffset(6, descriptionOffset);
        fbb.addOffset(7, category_statusOffset);
        fbb.addOffset(8, original_color_valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final costParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final category_statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final amount_paidParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final quantityParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final color_valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final original_color_valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = CategoryLocalModel(
          name: nameParam,
          cost: costParam,
          category_status: category_statusParam,
          amount_paid: amount_paidParam,
          quantity: quantityParam,
          description: descriptionParam,
          color_value: color_valueParam,
          original_color_value: original_color_valueParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<CategoryLocalModel>(
          object.paymentInfo,
          store,
          obx_int.RelInfo<PaymentInfoLocalModel>.toManyBacklink(2, object.id),
        );
        return object;
      },
    ),
    PaymentInfoLocalModel: obx_int.EntityDefinition<PaymentInfoLocalModel>(
      model: _entities[1],
      toOneRelations: (PaymentInfoLocalModel object) => [],
      toManyRelations: (PaymentInfoLocalModel object) => {
        obx_int.RelInfo<PaymentInfoLocalModel>.toMany(2, object.id):
            object.category_list,
      },
      getId: (PaymentInfoLocalModel object) => object.id,
      setId: (PaymentInfoLocalModel object, int id) {
        object.id = id;
      },
      objectToFB: (PaymentInfoLocalModel object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final phone_numberOffset = object.phone_number == null
            ? null
            : fbb.writeString(object.phone_number!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final payment_methodOffset = object.payment_method == null
            ? null
            : fbb.writeString(object.payment_method!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, phone_numberOffset);
        fbb.addInt64(3, object.date?.millisecondsSinceEpoch);
        fbb.addOffset(4, descriptionOffset);
        fbb.addOffset(5, payment_methodOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final phone_numberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final dateParam = dateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dateValue);
        final payment_methodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = PaymentInfoLocalModel(
          name: nameParam,
          phone_number: phone_numberParam,
          date: dateParam,
          payment_method: payment_methodParam,
          description: descriptionParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<PaymentInfoLocalModel>(
          object.category_list,
          store,
          obx_int.RelInfo<PaymentInfoLocalModel>.toMany(2, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CategoryLocalModel] entity fields to define ObjectBox queries.
class CategoryLocalModel_ {
  /// See [CategoryLocalModel.id].
  static final id = obx.QueryIntegerProperty<CategoryLocalModel>(
    _entities[0].properties[0],
  );

  /// See [CategoryLocalModel.name].
  static final name = obx.QueryStringProperty<CategoryLocalModel>(
    _entities[0].properties[1],
  );

  /// See [CategoryLocalModel.color_value].
  static final color_value = obx.QueryStringProperty<CategoryLocalModel>(
    _entities[0].properties[2],
  );

  /// See [CategoryLocalModel.quantity].
  static final quantity = obx.QueryDoubleProperty<CategoryLocalModel>(
    _entities[0].properties[3],
  );

  /// See [CategoryLocalModel.cost].
  static final cost = obx.QueryDoubleProperty<CategoryLocalModel>(
    _entities[0].properties[4],
  );

  /// See [CategoryLocalModel.amount_paid].
  static final amount_paid = obx.QueryDoubleProperty<CategoryLocalModel>(
    _entities[0].properties[5],
  );

  /// See [CategoryLocalModel.description].
  static final description = obx.QueryStringProperty<CategoryLocalModel>(
    _entities[0].properties[6],
  );

  /// See [CategoryLocalModel.category_status].
  static final category_status = obx.QueryStringProperty<CategoryLocalModel>(
    _entities[0].properties[7],
  );

  /// See [CategoryLocalModel.original_color_value].
  static final original_color_value =
      obx.QueryStringProperty<CategoryLocalModel>(_entities[0].properties[8]);
}

/// [PaymentInfoLocalModel] entity fields to define ObjectBox queries.
class PaymentInfoLocalModel_ {
  /// See [PaymentInfoLocalModel.id].
  static final id = obx.QueryIntegerProperty<PaymentInfoLocalModel>(
    _entities[1].properties[0],
  );

  /// See [PaymentInfoLocalModel.name].
  static final name = obx.QueryStringProperty<PaymentInfoLocalModel>(
    _entities[1].properties[1],
  );

  /// See [PaymentInfoLocalModel.phone_number].
  static final phone_number = obx.QueryStringProperty<PaymentInfoLocalModel>(
    _entities[1].properties[2],
  );

  /// See [PaymentInfoLocalModel.date].
  static final date = obx.QueryDateProperty<PaymentInfoLocalModel>(
    _entities[1].properties[3],
  );

  /// See [PaymentInfoLocalModel.description].
  static final description = obx.QueryStringProperty<PaymentInfoLocalModel>(
    _entities[1].properties[4],
  );

  /// See [PaymentInfoLocalModel.payment_method].
  static final payment_method = obx.QueryStringProperty<PaymentInfoLocalModel>(
    _entities[1].properties[5],
  );

  /// see [PaymentInfoLocalModel.category_list]
  static final category_list =
      obx.QueryRelationToMany<PaymentInfoLocalModel, CategoryLocalModel>(
        _entities[1].relations[0],
      );
}
